name: ci

on:
  push:
    tags:
      - v1
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        if: ${{ contains(github.ref, '/v') }}
        with:
          push: true
          tags: secanis/ssl-check-dashboard:latest,secanis/ssl-check-dashboard:${{ github.event.release.tag_name }}
      -
        name: Build
        id: docker_build_only
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: false
