name: ci

on:
    push:
        tags:
            - v0.*
            - v1.*
        branches:
            - "main"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Prepare Version
              id: sub
              uses: bluwy/substitute-string-action@v1
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  _input-text: ${{ github.ref_name }}
                  v: ""

            - name: Build and push
              id: docker_build_push
              uses: docker/build-push-action@v2
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  push: true
                  tags: secanis/ssl-check-dashboard:latest,secanis/ssl-check-dashboard:${{ github.ref_name  }}
            - name: Build
              id: docker_build_only
              uses: docker/build-push-action@v2
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  push: false
